name: Lint

on: [push]

jobs:
  lint:
    strategy:
        matrix:
          os: [ubuntu-latest]
          node-version: [20.x]
          pnpm-version: [8.x]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: npm install
        
      - name: Lint code
        run: npm run lint